version: 2

before:
  hooks:
    - go mod tidy

builds:
  - 
    id: bore-server
    binary: bore-server
    main: ./cmd/bore-server/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'main.AppVersion={{.Version}}'"
    targets:
      - go_first_class

  - 
    id: bore-client
    binary: bore
    main: ./cmd/bore/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'main.AppVersion={{.Version}}' -X 'bore/internal/client.BoreServerHost=app.trybore.com' -X 'bore/internal/client.WSScheme=wss'"
    targets:
      - go_first_class

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  format: "tar.gz"

signs:
  -
    cmd: cosign
    artifacts: checksum
    signature: "${artifact}.bundle"
    args:
      - sign-blob
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"

homebrew_casks:
  -
    name: bore
    binaries:
      - bore
    url:
      template: "https://github.com/aditya-ds-1806/bore/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/aditya-ds-1806/bore/"
    homepage: "https://trybore.com/"
    description: "Blazing fast, free TCP tunnel that exposes your localhost to the world"
    directory: Casks
    skip_upload: false
    repository:
      owner: Aditya-ds-1806
      name: homebrew-tap
      branch: "release/{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: Aditya-ds-1806
          name: homebrew-tap
          branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
      signing:
        enabled: false

report_sizes: true

changelog:
  use: github

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
