# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - 
    id: bore-server
    binary: bore-server
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'main.AppMode=server'"
    targets:
      - go_first_class

  - 
    id: bore-client
    binary: bore
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'main.AppMode=client' -X 'bore/internal/client.BoreServerHost=trybore.com' -X 'bore/internal/client.WSScheme=wss'"
    targets:
      - go_first_class
  
signs:
    cmd: cosign
    artifacts: archives
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"

report_sizes: true

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
